image: Visual Studio 2017

environment:
  EnableNuGetPackageRestore: true

install:
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

before_build:
    appveyor-retry nuget restore

platform:
  - Any CPU

configuration:
  - Release

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

before_package:
- cmd: >-
     msbuild /t:pack /p:Configuration=Release src/SimpleDbMigrations/SimpleDbMigrations.csproj

artifacts:
  - path: 'src\*\*\*\*\.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: +9kig6gQ94Phc/BUJ0x/k6mwLniwicBXwMGrbsuS+to+lv882j1oPMfoNkEM9ELK
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/